apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
        - name: product-api
          image: product-api:latest-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default

---
apiVersion: v1
kind: Service
metadata:
  name: product-api
spec:
  selector:
    app: product-api
  ports:
    - port: 80
      targetPort: 8081

#spec:
#  type: NodePort
#  selector:
#    app: product-api
#  ports:
#    - port: 8081       # Port inside cluster
#      targetPort: 8081 # Port exposed by your container
#      nodePort: 30081  # Port exposed on your host machine
